version: '3.9'
services:
  app:
    build: docker/Dockerfile
    container_name: fastapi
    ports:
      - "8000:8000"
    env_file:
      - src/.env
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: smit
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
